export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const MODE_HANDLER = "MODE_HANDLER";
export const TOKEN_USER_DATA_HANDLER = "TOKEN_USER_DATA_HANDLER";
export const LOADING = "LOADING";
