export const STATUS = {
  SUCCESS: "SUCCESS",
  FAILURE: "FAILURE",
  RECORD_NOT_FOUND: "RECORD_NOT_FOUND",
  BAD_REQUEST: "BAD_REQUEST",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
};
