const BASE_URL = process.env.REACT_APP_SERVICE_URL;
export const API_URL = {
  auth: {
    login: `${BASE_URL}/login`,
    logout: `${BASE_URL}/api/auth/logout`,
    tokenUser: `${BASE_URL}/api/auth/getUserByToken`,
  },
  userCheck: {
    breakIn: `${BASE_URL}/api/usercheck/breakIn`,
    checkIn: `${BASE_URL}/api/usercheck/checkIn`,
    checkOut: `${BASE_URL}/api/usercheck/checkOut`,
    breakOut: `${BASE_URL}/api/usercheck/breakOut`,
    userCheck: `${BASE_URL}/api/usercheck/checkStatus`,
  },
  addUser: {
    addOneUser: `${BASE_URL}/api/users/signup`,
    getAllUser: `${BASE_URL}/api/users`,
    getUserRole: `${BASE_URL}/api/userRole`,
    getOneUser: `${BASE_URL}/api/users`,
    usreProflieUpdate: `${BASE_URL}/api/users`,
    EditOneUser: `${BASE_URL}/api/users/updateSingupData`,
    DeleteOneUser: `${BASE_URL}/api/users`,
    usrePasswordChange: `${BASE_URL}/api/users/changePassword`,
    profileUpload: `${BASE_URL}/api/users/profileUpload`,
    updateuserLogs: `${BASE_URL}/api/usercheck/checkLogsUpdate`,
    userAttandance: `${BASE_URL}/api/usercheck/chackAttendance`,
  },
  leave: {
    getAdminLeaves: `${BASE_URL}/api/userLeave/allLeave`,
    getUserLeaves: `${BASE_URL}/api/userLeave`,
    addLeaves: `${BASE_URL}/api/userLeave`,
    editLeaves: `${BASE_URL}/api/userLeave/leaveUpdate`,
    deleteLeaves: `${BASE_URL}/api/userLeave/leaveDelete`,
    approveLeaves: `${BASE_URL}/api/userLeave`,
  },
  holiday: {
    deleteHoliday: `${BASE_URL}/api/holiday/deleteHoliday`,
    updateHoliday: `${BASE_URL}/api/holiday/updateHoliday`,
    getAllHolidays: `${BASE_URL}/api/holiday/getAllHolidays`,
    getOneHolidays: `${BASE_URL}/api/holiday/getAllHolidays`,
    addOneHoliday: `${BASE_URL}/api/holiday`,
  },
  project: {
    getAllProjects: `${BASE_URL}/api/project/`,
    addOneProject: `${BASE_URL}/api/project/`,
    editOneProject: `${BASE_URL}/api/project`,
    deleteOneProject: `${BASE_URL}/api/project`,
  },
  clients: {
    getAllClients: `${BASE_URL}/api/client/`,
  },
  tag: {
    getAllTag: `${BASE_URL}/api/tags`,
    getAllTagById: `${BASE_URL}/api/tags`,
    createTag: `${BASE_URL}/api/tags`,
    deleteTag: `${BASE_URL}/api/tags`,
    editOneTag: `${BASE_URL}/api/tags`,
  },
  toggle: {
    createToggle: `${BASE_URL}/api/toggle`,
    getAllToggle: `${BASE_URL}/api/toggle/getAll`,
    getByUserIdToggle: `${BASE_URL}/api/toggle`,
    DeleteToggle: `${BASE_URL}/api/toggle`,
    EditToggleData: `${BASE_URL}/api/toggle`,
  },
  extrastaffing: {
    getAllExtraStaffing: `${BASE_URL}/api/extra-staffing/getAllExtra_Staffing`,
    getOneUserExtraStaffing: `${BASE_URL}/api/extra-staffing`,
    addExtraStaffing: `${BASE_URL}/api/extra-staffing`,
    editExtraStaffing: `${BASE_URL}/api/extra-staffing/updateUser`,
    deleteExtraStaffing: `${BASE_URL}/api/extra-staffing/delete`,
    approveExtraStaffing: `${BASE_URL}/api/extra-staffing/isApprove_extraStaffing`,
  },
};
