export const CREATE_TOGGLE_DATA = "CREATE_TOGGLE_DATA";
export const GET_TOGGLE_DATA = "GET_TOGGLE_DATA";
export const GET_USERID_BY_TOGGLE_DATA = "GET_USERID_BY_TOGGLE_DATA";
export const LOADING = "LOADING";
